# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # to encode password of entity
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # Providers ? How will we allow the users to access data
    providers:
        user_provider:
            entity:
                class: AppBundle:User # Which entity is your provider referring to
#                property: username # What are you going to check against the database


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # This option is for users to authenticate anonymously
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

